---
- name: Create Docker Image
  hosts: all
  tasks:
    - name: Install Docker (Ubuntu)
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Install Docker (CentOS)
      yum:
        name: docker
        state: present
      when: ansible_distribution == "CentOS"
      become: true

    - name: Start Docker Service
      service:
        name: docker.service
        state: started
        enabled: true
      become: true

    - name: Copy Dockerfile to the remote host
      copy:
        src: Dockerfile
        dest: /home/dldperez/Dockerfile

    - name: copy static web page app files to remote hosts
      copy:
        src: ./static-web-app/
        dest: /home/dldperez/static-web-app/
        remote_src: no

    - name: Build Docker Image
      command:
        cmd: docker build -t webapp .
        chdir: /home/dldperez
      become: true

