- name: Install Docker SDK for Python
  hosts: all
  become: yes
  tasks:
    - name: Install pip on ubuntu
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install pip on centOS
      yum:
        name: python3-pip
        state: present
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Ensure Docker SDK for python is installed
      pip:
        name: docker
        state: present
        executable: pip3

